import moment from "moment";


export class EventStartNotificationSettings extends BaseSettings{
    constructor(id, date) {
        super(id, date);
        this.channelId = "event-start-ch";
    }
}

export class UpcomingEventNotificationSettings extends BaseSettings{
    constructor(id, date) {
        super(id, date);
        this.channelId = "upcoming-soon-ch";
    }
}

class BaseSettings {
    constructor(id, date) {
        this.Id = id;
        this.date = moment(date).toDate();

        // From the original code
        this.ticker = 'My Notification Ticker';
        this.autoCancel = true;
        this.vibrate = true;
        this.vibration = 300;
        this.groupSummary = false;
        this.ongoing = false;
        this.actions = ['Yes', 'No'];
        this.invokeApp = true;
        this.when = null;
        this.usesChronometer = false;
        this.timeoutAfter = null;
        this.category = '';
        this.playSound = true;
        this.soundName = 'default'
        this.number = 10;

        // Default values
        this.bigText = "My big text that will be shown when notification is expanded";
        this.subText = "This is a subText";
        this.largeIcon = "ic_launcher";
        this.smallIcon = "ic_notification";
        this.title = "Notification Title";
        this.message = "Notification Message";

        this.channelId = "event-start-ch";
    }
    setIcon(largeIcon, smallIcon) {
        this.largeIcon = largeIcon;
        this.smallIcon = smallIcon;
    }
    setText(bigText, subText) {
        this.bigText = bigText;
        this.subText = subText;
    }
    setTitleMessage(title, message) {
        this.title = title;
        this.message = message;
    }
    asDict() {
        return {
            /* Android Only Properties */
            channelId: this.channelId,
            ticker: this.ticker, // (optional)
            autoCancel: this.autoCancel, // (optional) default: true
            largeIcon: this.largeIcon, // (optional) default: "ic_launcher"
            smallIcon: this.smallIcon, // (optional) default: "ic_notification" with fallback for "ic_launcher"
            bigText: this.bigText, // (optional) default: "message" prop
            subText: this.subText, // (optional) default: none
            // color: 'red', // (optional) default: system default
            vibrate: this.vibrate, // (optional) default: true
            vibration: this.vibration, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
            tag: 'event', // (optional) add tag to message
            group: 'group', // (optional) add group to message
            groupSummary: this.groupSummary, // (optional) set this notification to be the group summary for a group of notifications, default: false
            ongoing: this.ongoing, // (optional) set whether this is an "ongoing" notification
            actions: this.actions, // (Android only) See the doc for notification actions to know more
            invokeApp: this.invokeApp, // (optional) This enable click on actions to bring back the application to foreground or stay in background, default: true

            when: this.when, // (optional) Add a timestamp pertaining to the notification (usually the time the event occurred). For apps targeting Build.VERSION_CODES.N and above, this time is not shown anymore by default and must be opted into by using `showWhen`, default: null.
            usesChronometer: this.usesChronometer, // (optional) Show the `when` field as a stopwatch. Instead of presenting `when` as a timestamp, the notification will show an automatically updating display of the minutes and seconds since when. Useful when showing an elapsed time (like an ongoing phone call), default: false.
            timeoutAfter: this.timeoutAfter, // (optional) Specifies a duration in milliseconds after which this notification should be canceled, if it is not already canceled, default: null

            /* iOS only properties */
            category: this.category, // (optional) default: empty string

            /* iOS and Android properties */
            id: this.Id, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
            title: this.title, // (optional)
            message: this.message, // (required)
            userInfo: {screen: 'home'}, // (optional) default: {} (using null throws a JSON value '<null>' error)
            playSound: this.playSound, // (optional) default: true
            soundName: this.soundName, // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
            number: this.number, // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
        }
    }
}
